SELECT * FROM "Customer_behavior";



-- Q1. Total revenue generated by male vs female customers
SELECT
    gender,
    SUM("purchase-amount") AS total_revenue
FROM "Customer_behavior"
GROUP BY gender
ORDER BY total_revenue DESC;






-- Q2. Customers who used a discount but still spent more than average
SELECT
    "customer-id",
    "purchase-amount",
    "discount-applied"
FROM "Customer_behavior"
WHERE "discount-applied" = 'Yes'
  AND "purchase-amount" > (
      SELECT AVG("purchase-amount")
      FROM "Customer_behavior"
  )
ORDER BY "purchase-amount" asc;







-- Q3. Top 5 products with the highest average review rating
SELECT
    "item-purchased",
    AVG("review-rating") AS avg_review_rating
FROM "Customer_behavior"
GROUP BY "item-purchased"
ORDER BY avg_review_rating DESC
LIMIT 5;








-- Q4. Do subscribed customers spend more?
SELECT
    "subscription-status",
    AVG("purchase-amount") AS avg_spend,
    SUM("purchase-amount") AS total_revenue,
    COUNT(*) AS total_purchases
FROM "Customer_behavior"
GROUP BY "subscription-status"
ORDER BY avg_spend DESC;








-- Q5. Top 5 products with highest percentage of discounted purchases
SELECT
    "item-purchased",
    COUNT(*) AS total_purchases,
    SUM(
        CASE
            WHEN "discount-applied" = 'Yes' THEN 1
            ELSE 0
        END
    ) AS discounted_purchases,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN "discount-applied" = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM "Customer_behavior"
GROUP BY "item-purchased"
ORDER BY discount_percentage DESC
LIMIT 5;










-- Q6. Segment customers into New, Returning, and Loyal
SELECT
    CASE
        WHEN "previous-purchases" <= 1 THEN 'New'
        WHEN "previous-purchases" BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    
    COUNT(DISTINCT "customer-id") AS total_customers

FROM "Customer_behavior"

GROUP BY customer_segment

ORDER BY total_customers DESC;









-- Q7. Top 3 most purchased products within each category
WITH product_counts AS (
    SELECT
        category,
        "item-purchased",
        COUNT(*) AS purchase_count
    FROM "Customer_behavior"
    GROUP BY category, "item-purchased"
),

ranked_products AS (
    SELECT
        category,
        "item-purchased",
        purchase_count,
        RANK() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS product_rank
    FROM product_counts
)

SELECT
    category,
    "item-purchased",
    purchase_count,
    product_rank
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;

















-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    "subscription-status",
    COUNT(DISTINCT "customer-id") AS total_customers,
    ROUND(
        100.0 * COUNT(DISTINCT "customer-id")
        / SUM(COUNT(DISTINCT "customer-id")) OVER (),
        2
    ) AS percentage
FROM "Customer_behavior"
WHERE "previous-purchases" > 5
GROUP BY "subscription-status"
ORDER BY total_customers DESC;
